-- Schema initial pour les tests CI (table users utilisée par db_service)
-- À exécuter une seule fois (idempotent avec IF NOT EXISTS)

CREATE TABLE IF NOT EXISTS users (
    email TEXT PRIMARY KEY,
    password TEXT,
    full_name TEXT,
    role TEXT DEFAULT 'client',
    gender TEXT,
    country_code TEXT,
    coach_gender_preference TEXT,
    profile_completed BOOLEAN DEFAULT false,
    verified BOOLEAN DEFAULT false,
    email_verified BOOLEAN DEFAULT false,
    bio TEXT,
    city TEXT,
    instagram_url TEXT,
    price_from INTEGER DEFAULT 50,
    radius_km INTEGER DEFAULT 10,
    profile_photo_url TEXT,
    profile_slug TEXT,
    specialties TEXT,
    selected_gym_ids TEXT,
    selected_gyms_data TEXT,
    subscription_status TEXT DEFAULT 'pending_payment',
    stripe_customer_id TEXT,
    stripe_subscription_id TEXT,
    subscription_period_end TIMESTAMP,
    otp_code TEXT,
    otp_expiry TIMESTAMP,
    pending_bookings TEXT,
    confirmed_bookings TEXT,
    rejected_bookings TEXT,
    unavailable_days TEXT,
    unavailable_slots TEXT,
    payment_mode TEXT DEFAULT 'disabled',
    session_duration INTEGER DEFAULT 60,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    stripe_connect_account_id TEXT,
    stripe_connect_status TEXT,
    stripe_connect_charges_enabled BOOLEAN DEFAULT false,
    stripe_connect_payouts_enabled BOOLEAN DEFAULT false,
    stripe_connect_details_submitted BOOLEAN DEFAULT false
);
