name: reminders_process_cron

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  call-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Call reminders_process endpoint
        run: |
          curl -X GET https://fitmatch.fr/api/reminders_process
